// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7U9CxCSNEXpovuhJN7QZ6IVT-b06WdLE',
    appId: '1:464773386660:web:0af609b33b3f95ae343131',
    messagingSenderId: '464773386660',
    projectId: 'quanly-suckhoe-tapluyen',
    authDomain: 'quanly-suckhoe-tapluyen.firebaseapp.com',
    storageBucket: 'quanly-suckhoe-tapluyen.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe3-gD49wDRPWn4qN2iK66Tfjek3pxzAc',
    appId: '1:464773386660:android:0ba00f09fd7368fa343131',
    messagingSenderId: '464773386660',
    projectId: 'quanly-suckhoe-tapluyen',
    storageBucket: 'quanly-suckhoe-tapluyen.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGtQIkL1AM8f_4a2MNgvBqkOVvccWLRM8',
    appId: '1:464773386660:ios:69a5ff9f6a2be526343131',
    messagingSenderId: '464773386660',
    projectId: 'quanly-suckhoe-tapluyen',
    storageBucket: 'quanly-suckhoe-tapluyen.firebasestorage.app',
    iosBundleId: 'com.example.ungdungluyentapSuckhoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGtQIkL1AM8f_4a2MNgvBqkOVvccWLRM8',
    appId: '1:464773386660:ios:69a5ff9f6a2be526343131',
    messagingSenderId: '464773386660',
    projectId: 'quanly-suckhoe-tapluyen',
    storageBucket: 'quanly-suckhoe-tapluyen.firebasestorage.app',
    iosBundleId: 'com.example.ungdungluyentapSuckhoe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7U9CxCSNEXpovuhJN7QZ6IVT-b06WdLE',
    appId: '1:464773386660:web:cdabb757c27d4208343131',
    messagingSenderId: '464773386660',
    projectId: 'quanly-suckhoe-tapluyen',
    authDomain: 'quanly-suckhoe-tapluyen.firebaseapp.com',
    storageBucket: 'quanly-suckhoe-tapluyen.firebasestorage.app',
  );
}
